version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    image: xavierguertin/wildfirevisualization-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - CONFIG_FILE_PATH=/var/config/app-config.json
      - GEOSERVER_DATA_DIR=/var/geoserver/data_dir/tiffs
      - GEOSERVER_URL=http://geoserver:8080/geoserver
    networks:
      - app-network
    volumes:
      - ./config:/var/config/
      - ./apps/geoserver_data/tiffs:/var/geoserver/data_dir/tiffs
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 20
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "0.5"

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
        NEXT_PUBLIC_GEOSERVER_URL: http://localhost:8090/geoserver/Default/wms
        NEXT_PUBLIC_TILESERVER_URL: http://localhost:8081/data/OAM-World-1-8-min-J80
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
      - NEXT_PUBLIC_GEOSERVER_URL=http://localhost:8091/geoserver/Default/wms
      - NEXT_PUBLIC_TILESERVER_URL=http://localhost:8081/data/OAM-World-1-8-min-J80
    image: xavierguertin/wildfirevisualization-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: "256M"
          cpus: "0.25"

  db:
    image: ghcr.io/stac-utils/pgstac:v0.9.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: postgres
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - ./apps/db/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"

  tileserver-init:
    image: curlimages/curl
    container_name: tileserver-init
    user: root
    volumes:
      - ./apps/tileserver/layers:/tileserver
    entrypoint: [ "/bin/sh", "-c", "sh /tileserver/download_tiles.sh" ]
    networks:
      - app-network

  tileserver:
    image: maptiler/tileserver-gl
    container_name: tileserver
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./apps/tileserver/layers:/data
    depends_on:
      tileserver-init:
        condition: service_completed_successfully
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "0.5"

  geoserver:
    image: kartoza/geoserver:2.23.1
    ports:
      - "8091:8080"
    environment:
      - GEOSERVER_ADMIN_USER=geoserver
      - GEOSERVER_ADMIN_PASSWORD=password
      - GEOSERVER_DATA_DIR=/var/geoserver/data_dir
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
      - DISABLE_FIGLET_BANNER=true  # Explicitly disable figlet
    networks:
      - app-network
    volumes:
      - ./apps/geoserver_data:/var/geoserver/data_dir
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -s http://localhost:8080/geoserver/web/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: "3G"
          cpus: "1"

networks:
  app-network:
    driver: bridge
