version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    image: xavierguertin/wildfirevisualization-backend:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    image: xavierguertin/wildfirevisualization-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  geoserver:
    image: kartoza/geoserver:latest
    ports:
      - "8090:8080"
    environment:
      GEOSERVER_ADMIN_USER: geoserver
      GEOSERVER_ADMIN_PASSWORD: password

networks:
  app-network:
    driver: bridge
