# SonarCloud URL and Token
sonar.host.url=https://sonarcloud.io

# Project Sources for Java and TypeScript
sonar.sources=apps/frontend/src,apps/backend/src
sonar.language=java,typescript

# Test and Coverage Configuration for TypeScript (frontend)
sonar.tests=apps/frontend/__tests__
sonar.test.inclusions=apps/frontend/src/**/*.test.tsx,apps/frontend/src/**/*.spec.tsx
sonar.typescript.lcov.reportPaths=coverage/apps/frontend/lcov.info

# Test and Coverage Configuration for Java (backend)
sonar.java.binaries=apps/backend/target/classes
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=apps/backend/target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=apps/backend/target/site/jacoco/jacoco.xml


# Code Coverage Minimum Thresholds
sonar.coverage.exclusions=node_modules/**,dist/**
sonar.coverage.minimumCoverage=80

