# SonarCloud URL and Token
sonar.host.url=https://sonarcloud.io

# Project Sources for Java
sonar.sources=apps/backend/src/main
sonar.language=java

sonar.tests=apps/backend/src/test

# Test and Coverage Configuration for Java (backend)
sonar.java.binaries=apps/backend/target/classes
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=apps/backend/target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=apps/backend/target/site/jacoco/jacoco.xml


# Code Coverage Minimum Thresholds
sonar.coverage.exclusions=node_modules/**,dist/**,**/WebConfig.java,**/BackendApplication.java
sonar.coverage.minimumCoverage=80

