# Project metadata
sonar.projectName=Frontend Application

# SonarCloud URL and Token
sonar.host.url=https://sonarcloud.io

# Source directories
sonar.sources=apps/frontend/src/app/components
sonar.tests=apps/frontend/__tests__
sonar.language=typescript

# Paths for test and coverage reports
sonar.typescript.lcov.reportPaths=coverage/apps/frontend/lcov.info

# Inclusion/exclusion settings
sonar.test.inclusions=apps/frontend/src/**/*.test.tsx,apps/frontend/src/**/*.spec.tsx
sonar.coverage.exclusions=node_modules/**,dist/**,apps/frontend/src/app/components/MapContext.tsx
sonar.coverage.minimumCoverage=80

# Exclude specific files from analysis
sonar.exclusions=apps/frontend/src/app/layout.tsx

# Encoding
sonar.sourceEncoding=UTF-8
