name: CI

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install --legacy-peer-deps

      - name: Lint Frontend Projects
        run: npx nx lint frontend

      - name: Build Frontend
        run: npx nx build frontend

      - name: Test Frontend
        run: npx nx test frontend

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarCloud Scan Frontend
        env:
          SONAR_TOKEN_FRONTEND: ${{ secrets.SONAR_TOKEN_FRONTEND }}
          SONAR_PROJECT_KEY_FRONTEND: ${{ secrets.SONAR_PROJECT_KEY_FRONTEND }}
          SONAR_ORGANIZATION_KEY_FRONTEND: ${{ secrets.SONAR_ORGANIZATION_KEY_FRONTEND }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          npx sonar-scanner -X \
            -Dproject.settings=sonar-project-frontend.properties \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY_FRONTEND \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY_FRONTEND \
            -Dsonar.login=$SONAR_TOKEN_FRONTEND \
            -Dsonar.branch.name=$BRANCH_NAME \
            -Dsonar.qualitygate.wait=true

  backend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install --legacy-peer-deps

      - name: Lint Backend Projects
        run: npx nx lint backend

      - name: Build Backend
        run: npx nx build backend

      - name: Test Backend
        run: npx nx test backend

      - name: Verify Backend Coverage Files
        run: ls -R apps/backend/target/site/jacoco/

      - name: SonarCloud Scan Backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          npx sonar-scanner -X \
            -Dproject.settings=sonar-project-backend.properties \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=$BRANCH_NAME \
            -Dsonar.qualitygate.wait=true
