name: CI

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - run: npm install --legacy-peer-deps

      - name: Install Cypress Binary
        run: npx cypress install

      - name: Lint Frontend Projects
        run: npx nx lint frontend

      - name: Build Frontend
        run: npx nx build frontend

      - name: Test Frontend
        run: npx nx test frontend --code-coverage  # Ensure code coverage reporting

      - name: End-to-End Tests
        run: npx nx e2e frontend-e2e

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarCloud Scan Frontend
        run: |
          npx sonar-scanner -X \
            -Dproject.settings=sonar-project-frontend.properties \
            -Dsonar.projectKey="wildfirefrontendscanner_wildfirefrontendscanner" \
            -Dsonar.organization="wildfirefrontendscanner" \
            -Dsonar.login="9b48e7ee9628e35278f48d2951ea3e82db0be2f6" \
            -Dsonar.branch.name="${{ github.ref_name }}"

      # Enforce Quality Gate
      - name: Check SonarCloud Quality Gate
        uses: sonarsource/sonarcloud-quality-gate-action@master
        with:
          sonar_token: '9b48e7ee9628e35278f48d2951ea3e82db0be2f6'

  backend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Node.js Dependencies
        run: npm install --legacy-peer-deps

      - name: Lint Backend Projects
        run: npx nx lint backend

      - name: Build Backend
        run: npx nx build backend

      - name: Test Backend
        run: npx nx test backend --code-coverage

      - name: List Backend Coverage Files
        run: ls -R apps/backend/target/site/jacoco/

      - name: SonarCloud Scan Backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          npx sonar-scanner -X \
            -Dproject.settings=sonar-project-backend.properties \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=$BRANCH_NAME

      - name: Check SonarCloud Quality Gate
        uses: sonarsource/sonarcloud-quality-gate-action@master
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
