name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Installation
      run: docker/setup-buildx-action@v1

    - name: Docker Compose Installation
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build the Docker image
      run: docker-compose up --build -d

    - name: Tear Down the Docker-Compose
      if: always()
      run: docker-compose down