name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker-compose up --build -d

    - name: Tear Down the Docker-Compose
      if: always()
      run: docker-compose down